# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91b68b4c8da94ad8178945850655ea52e2c509958d68d64a54c7bbc9fe62a7d030ebffda25606ebb6af54e60bc0e1691287a4a5c9fdc65b96d0a32fd19f6b265

test:
  secret_key_base: 7f6bd9b13942654c078ebd4788af639286d9f9f02d736f151309a8fa9f551180945d350a4b8259534b73a3c369fe9509f14f2b6750e99831c1787381619b4ea4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
